### PR TITLE
99 fix front button on browser

### PR DESCRIPTION
**Pull request by MahdyZ7**
navigating using the front and back buttons on the browser works now

### CODE REVIEW

**Comment by Salem-1** [comment]
the front button work fine with 1 V 1, however The front doesn't work with single player, with tournament it works but throw an uncought exception

**Comment by MahdyZ7** [comment]
@Salem-1 done. please review

**Comment by Salem-1** [comment]
The forward button doesn't work with single player, if you fix this issue will approve the pull request, the below notes related to tournament appeared with front and back


When fill players then click start tournament then back then front it open the tournament with uncought exception and empty players which shouldn't happen, here is the error:
Uncaught (in promise) Error: error: fetching players for the tournament
    at startTournament (tournament_algorithm.js:39:11)
    at initTournament (tournament_algorithm.js:10:5)
    at tournament_algorithm.js:2:3
When launch tournament then play and a player win then click back the tournament page with alert cought exception  "invalid players array size"and the tournament page appear without css which is ugly

**Comment by Salem-1** [comment]
The single player working fine, will approve this pull request, however the tournament front button still throws an error, we can fix it in another issue inshalla

**Pull request merged**
